### ISSUE TITLE
Genderei, Klammern

### ISSUE THREAD

**Issue by novoid** [covid-at-home/covid-zu-hause#11]
Hi,

Ich persönlich finde Formen wie "eine\*n Ärzt\*in" oder "Freunde\*innen" eine fürchterliche Art und Weise, mit der deutschen Sprache umzugehen. Auch als Leser fühle ich mich nicht ernst genommen, da mein Unterbewusstsein über jede dieser Dinger stolpert und von dem guten Textinhalt durch seine Form stark ablenkt.
Ich respektiere aber den Gedanken, die Frauen explizit miteinzubinden.
Wenn nicht für dieses aber dann für das nächste Projekt: verwendet doch bitte einfach die reine weibliche Form. Richtige Männer sollten das aushalten (Klischee intended). Das erleichtert das Lesen ungemein und jedem ist klar, welche Betonung das bewirkt.

Noch ein anderer Kommentar: verwendet doch weniger Bemerkungen in Klammern. Das interpretiert man als Unsicherheit (soll der Text nun rein oder ist der doch nichts für den Satz?). Frei nach Yoda: Text rein oder kein Text rein, es gibt kein Versuchen. ;-)

**Comment by ropg** [comment]
Wir benützen Klammern um an zu deuten das etwas eher eine Seitengedanke bzw Seitenerklärung ist. Ich weis das das auf Englisch mehr gemacht wird als auf Deutsch, aber werde trotzdem schauen ob's nicht stellen gibt wo's auch auf Englisch besser ist ohne.

Was Gendern angeht: ich bin hier nicht aufgewachsen, mein Deutsch ist machmal eh für die Tonne und mir ist halbwegs egal bis amusant was ihr hier alle mit eure Sprache macht. Die Auswahl ist eher wild (binnen-I, mehrere Paarformen, Strich, Sternchen, etc) und mir wurde erklärt das man das jetzt aktuell mit Sternchen machen soll, damit auch leute deren Genderidentität weniger binär ist sich optimal wohl fühlen. Durchaus von jemanden die darauf denn die ganze Site durchgegangen ist um das einheitlich zu machen; es war ein komplettes durcheinander. 

Ich sehe selber wenig Indizen dafür das solche Einflussnahmen auf der Sprache die Welt verändern können. Sprache lebt, und Aktivismus hat seinen Zweck aber ist meiner Meinung nach überwertet. Pragmatisch ist es aber so das man nie alle glücklich machen kann und das Leute die das nichts finden sowie es jetzt in der text ist im Schnitt weniger (oder weniger vokal) unzufrieden sind.

Ich frag mal bei den Deutsche*n um mich herum ein paar mehr Meinungen, auch bzgl "nur weibliche Form", aber tendiere danach das jetzt so zu lassen...

**Comment by novoid** [comment]
> Wir benützen Klammern um an zu deuten das etwas eher eine Seitengedanke bzw Seitenerklärung ist. Ich weis das das auf Englisch mehr gemacht wird als auf Deutsch, aber werde trotzdem schauen ob's nicht stellen gibt wo's auch auf Englisch besser ist ohne.

Es ist mir klar, aus welcher Motivation du als Schreiber das machst. ;-)
Habe ich früher auch selbst so gemacht.
Nur betrachte das aus Leser-Perspektive: was sagt mir die Klammer? Soll ich das erstmal weglassen und dann erst nachlesen, wenn der restliche Satz mir zu wenig Information gebracht hat? Soll ich das immer mitlesen? Du siehst - aus Leserperspektive machen die Klammern keinen Mehrwert aus. Im Gegenteil: man kann diese Klammern als Schachtelsätze interpretieren. Und die verschlimmern die Lesbarkeit vom Inhalt.

Bitte mir nicht negativ auslegen! Mir geht es immer nur darum, dass die Leser den wunderbaren **Inhalt** besser aufnehmen können. Komplizierte, lange, verschachtelte Sätze verhindern das genauso effektiv wie diese Form von Gendern: 

> Was Gendern angeht: ich bin hier nicht aufgewachsen, mein Deutsch ist machmal eh für die Tonne und mir ist halbwegs egal bis amusant was ihr hier alle mit eure Sprache macht. Die Auswahl ist eher wild (binnen-I, mehrere Paarformen, Strich, Sternchen, etc)

Tell news ;-)

> und mir wurde erklärt das man das jetzt aktuell mit Sternchen machen soll, damit auch leute deren Genderidentität weniger binär ist sich optimal wohl fühlen. Durchaus von jemanden die darauf denn die ganze Site durchgegangen ist um das einheitlich zu machen; es war ein komplettes durcheinander.

I see. Schon oft so gehört.

> Ich sehe selber wenig Indizen dafür das solche Einflussnahmen auf der Sprache die Welt verändern können. Sprache lebt, und Aktivismus hat seinen Zweck aber ist meiner Meinung nach überwertet. Pragmatisch ist es aber so das man nie alle glücklich machen kann und das Leute die das nichts finden sowie es jetzt in der text ist im Schnitt weniger (oder weniger vokal) unzufrieden sind.

Zwei Dinge (die voneinander unabhängig sind):

Erstens: die Form beeinflusst in großem Maße die Fähigkeit, dass der Textinhalt beim Leser ins Hirn gelangen kann. Da gibt es wunderbare Studien aus dem Bereich der Typografie und Schriftenlehre. Das variiert zwischen 15 und 85 bis bestenfalls 90 Prozent. Das ist auch der Grund, weshalb man die zentralen Punkte in einem Text wiederholt einbringen muss. Damit stellt man sicher, dass diese zentralen Punkte sicher nicht in den Bereichen landen, die beim Leser nicht ankommen.

In anderen Worten: ausschließlich durch die Form, Farbe, Schriftwahl, und so weiter kann man beeinflussen, ob nur 15 Prozent des Inhaltes vom Leser aufgenommen wird oder bestenfalls 90 Prozent. Der Unterschied zwischen einer Katastroophe und einem guten Ergebnis hängt hier weder von der Formulierung, noch von anderen Buchstaben ab. Wir sprechen hier vom selben Text. 

Umgesetzt auf das Verändern der Schriftsprache mit diesen Gender-basierten Dingen passiert hier ebenso ein negativer Einfluss. Das bedeutet, dass _euch explizit der Gender-Gedankte immer mehr Wert ist als der Inhalt von euren Texten_. Das finde ich sehr schade. Im Extremfall kann das bei eurem Inhalt sogar Leben kosten.

 Nehmen wir folgendes Beispiel:

> Unter führenden Epidemiolog*innen und anderen relevanten Expert*innen besteht jedoch ...

Das menschiche Hirn kann nicht anders, als über diese Sterne zu stolpern. Das sieht dann in etwa so aus:

> Unter führenden Epidemiolog<UNS IST GENDERN WICHTIG!> und anderen relevanten Expert<UNS IST GENDERN WICHTIG!> besteht jedoch ...

Dass damit der Inhalt auf der Strecke bleibt, ist offensichtlich.

Zweitens: Ich betone weiterhin, dass das komplett unabhängig gesehen werden muss von meinen obigen Argument. Meine persönliche Meinung zu dem Thema ist, dass wir es nicht allen Schneeflocken auf diese Art recht machen können. Ansonsten hört Sprache auf, zu funktionieren. Geschrieben oder gesprochen, das ist egal. Es gibt eine momentane Strömung, die meiner Meinung nach wieder abflachen wird und danach ein ständiges Nischendasein fristen wird: _wir müssen doch auch auf xxx sprachlich Rücksicht nehmen, damit sie sich nicht weniger Wertig vorkommen._ I beg to differ.

Deshalb mein Vorschlag zur Güte als Kompromiss: nehmt doch als Ausgleich die reine weibliche Form. Es tut mir leid für Randgruppen, die sich weder noch zugehörig fühlen aber Rücksichtnahme hat auch Grenzen.

Ein sehr hartes Gegenargument wäre, dass diese Randgruppen durch den Genderwahn die Verständlichkeit aller Menschen vermindern, was auch eine Unterdrückung darstellt. Irgendwann hört sich der Spaß auf. 

Das ist mein persönlicher Zugang und hier kann jeder eine andere Meinung haben. Das gilt allerdings nicht für Argument eins. Das sind Fakten und keine persönliche Meinung.

> Ich frag mal bei den Deutsche*n um mich herum ein paar mehr Meinungen, auch bzgl "nur weibliche Form", aber tendiere danach das jetzt so zu lassen...

Lass es. Ich wollte den Hinweis für zukünftige Projekte geben.
